plugin: passing labels to envoyfilter
slime-io/slime pull request #162
Opened 2022-07-07 09:28 UTC by believening

some scenarios require pass-through of resource metadata, especially for labels, which can be used to indicate that multiple instances of different types of resources belong to the same group.

2022-07-12 02:00 UTC, cywang1905 requested changes

2022-07-12 02:00 UTC, cywang1905 commented on staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go
>  	found := &v1alpha3.EnvoyFilter{}
make plugin change another commit, more clearly

2022-07-12 02:16 UTC, cywang1905 commented on framework/model/config.go
> +var passthroughLabelPattern = regexp.MustCompile(os.Getenv("SLIME_PASS_LBL_REG"))
seems we can paas through env to module 
```yaml
          {{- if $.Values.env }}
          {{- toYaml $.Values.env | nindent 12 }}
          {{- end }}
```

2022-07-12 02:18 UTC, cywang1905 commented on framework/model/config.go
> +var passthroughLabelPattern = regexp.MustCompile(os.Getenv("SLIME_PASS_LBL_REG"))
https://github.com/slime-io/slime/pull/143

2022-07-12 02:28 UTC, believening commented on staging/src/slime.io/slime/modules/plugin/controllers/pluginmanager_controller.go
>  	found := &v1alpha3.EnvoyFilter{}
done, split2

2022-07-12 03:47 UTC, believening commented on framework/model/config.go
> +var passthroughLabelPattern = regexp.MustCompile(os.Getenv("SLIME_PASS_LBL_REG"))
updated describe

2022-07-14 02:25 UTC, believening commented on framework/model/config.go
> +		if !passthroughLabelPattern.MatchString(k) {
based on regular expressions we can meet the scenario： `(project|network)`

2022-07-14 12:19 UTC, cywang1905 approved these changes

2022-07-17 16:57 UTC, merged