support crds version apiextensions.k8s.io/v1
slime-io/slime pull request #197
Opened 2022-10-21 02:18 UTC by MouceL

2022-10-21 09:50 UTC, cywang1905 requested changes

2022-10-21 09:50 UTC, cywang1905 commented on install/init/crds-v1.yaml
> +      - slb
every crd need shortNames

2022-10-24 12:13 UTC, cywang1905 approved these changes

2022-10-26 06:03 UTC, YonkaFang commented on install/init/crds-v1.yaml
> +---
There should be a corresponding change to the installation introduction document

2022-10-26 09:28 UTC, merged